### ISSUE TITLE
Implement Objectool 0.5 support

### ISSUE THREAD

**Issue by TheLX5** [TheLX5/Star-Coins#2]
Objectool 0.5 is yet to be released. I'll gladly add support to it once it's out.

However, I won't go back to Objectool 0.4.

**Comment by TheLX5** [comment]
https://www.smwcentral.net/?p=section&a=details&id=24217

Objectool0.5 was released.

**Comment by MarioFanGamer** [comment]
ObjecTool support has been added with [59f3992](https://github.com/TheLX5/Star-Coins/commit/59f3992ee8f6dc5d66e91098c116af14c8c392d7).
